Tue Jul 11 12:35:49 2023
Emscripten-1.0-wasm32-32bit
Ren'Py 7.5.3.22090809u
 

Bootstrap to the start of init.init took 0.00s
Early init took 0.01s
Loader init took 0.08s
import encodings.utf_32_be # precompiled from /lib/python2.7/encodings/utf_32_be.pyo
Loading error handling took 0.25s
Loading script took 11.60s
Loading save slot metadata. took 0.00s
Loading persistent took 0.00s
import tarfile # precompiled from /lib/python2.7/tarfile.pyo
Faled to initialize steam: ImportError('No module named ctypes',)
Set script version to: (7, 3, 5)
Running init code took 0.31s
Loading analysis data took 0.00s
Analyze and compile ATL took 0.11s
Index archives took 0.00s
Dump and make backups. took 0.00s
Cleaning cache took 0.00s
Making clean stores took 0.00s
Initial gc. took 0.10s
DPI scale factor: 1.000000
Creating interface object took 0.00s
Cleaning stores took 0.00s
Init translation took 0.14s
Build styles took 0.01s
Load screen analysis took 0.00s
Analyze screens took 0.12s
Save screen analysis took 0.16s
Prepare screens took 0.95s
Save pyanalysis. took 0.19s
Save bytecode. took 0.08s
Running _start took 0.01s
import renpy.audio.webaudio # precompiled from ./renpy/audio/webaudio.pyo
Interface start took 0.14s
import renpy.gl.gldraw # builtin
import renpy.gl.gltexture # builtin
import renpy.gl.glfunctions # precompiled from ./renpy/gl/glfunctions.pyo
import renpy.gl.glrtt_copy # builtin
import renpy.gl.glrtt_fbo # builtin
import renpy.gl.glenviron_shader # builtin

Initializing gles renderer:
primary display bounds: (0, 0, 1920, 1080)
swap interval: 1 frames
Windowed mode.
UGUU couldn't find glFlushMappedBufferRange: No OpenGL context has been made current
UGUU couldn't find glGetBufferPointerv: No OpenGL context has been made current
UGUU couldn't find glMapBufferRange: No OpenGL context has been made current
UGUU couldn't find glUnmapBuffer: No OpenGL context has been made current
Vendor: 'Mozilla'
Renderer: 'ANGLE (NVIDIA, NVIDIA GeForce GTX 980 Direct3D11 vs_5_0 ps_5_0)'
Version: 'OpenGL ES 2.0 (WebGL 1.0)'
Display Info: None
Number of texture units: 16
Using shader environment.
Using FBO RTT.
Root FBO is: 0
FBO Maximum Texture Size: 2048
Using gles renderer.
Texture testing:
- Hardware max texture size: 16384
- 64px textures work.
- 128px textures work.
- 256px textures work.
- 512px textures work.
- 1024px textures work.
- 2048px textures work.
Screen sizes: virtual=(1920, 1080) physical=(1920, 923) drawable=(1920, 923)
Root FBO is: 0
FBO Maximum Texture Size: 2048

Full traceback:
  File "/game/chapter_01.rpyc", line 1594, in script
  File "renpy/ast.py", line 921, in execute
  File "renpy/exports.py", line 1373, in say
  File "renpy/character.py", line 1266, in __call__
  File "renpy/character.py", line 930, in do_display
  File "renpy/character.py", line 666, in display_say
  File "renpy/ui.py", line 299, in interact
  File "renpy/display\core.py", line 3377, in interact
  File "renpy/display\core.py", line 3876, in interact_core
  File "renpy/webloader.py", line 222, in process_downloaded_resources
IOError: Download error: network error ('images/base_game/gui/screen_home_hr/mn_home_hr_rechph_idle.png' > '/game/images/base_game/gui/screen_home_hr/mn_home_hr_rechph_idle.png')

While running game code:
IOError: Download error: network error ('images/base_game/gui/screen_home_hr/mn_home_hr_rechph_idle.png' > '/game/images/base_game/gui/screen_home_hr/mn_home_hr_rechph_idle.png')
While handling exception:
Traceback (most recent call last):
  File "renpy/display\error.py", line 147, in report_exception
  File "renpy/game.py", line 286, in invoke_in_new_context
  File "renpy/display\error.py", line 48, in call_exception_screen
  File "renpy/ui.py", line 299, in interact
  File "renpy/display\core.py", line 3377, in interact
  File "renpy/display\core.py", line 3876, in interact_core
  File "renpy/webloader.py", line 222, in process_downloaded_resources
IOError: Download error: network error ('images/base_game/gui/screen_home_hr/mn_home_hr_rechph_hover.png' > '/game/images/base_game/gui/screen_home_hr/mn_home_hr_rechph_hover.png')

Full traceback:
  File "renpy/bootstrap.py", line 277, in bootstrap
  File "renpy/main.py", line 660, in main
  File "renpy/main.py", line 146, in run
  File "renpy/execution.py", line 938, in run_context
  File "/game/chapter_01.rpyc", line 1594, in script
  File "/game/chapter_01.rpyc", line 1594, in script
  File "renpy/ast.py", line 921, in execute
  File "renpy/exports.py", line 1373, in say
  File "renpy/character.py", line 1266, in __call__
  File "renpy/character.py", line 930, in do_display
  File "renpy/character.py", line 666, in display_say
  File "renpy/ui.py", line 299, in interact
  File "renpy/display\core.py", line 3377, in interact
  File "renpy/display\core.py", line 3876, in interact_core
  File "renpy/webloader.py", line 222, in process_downloaded_resources
IOError: Download error: network error ('images/base_game/gui/screen_home_hr/mn_home_hr_rechph_idle.png' > '/game/images/base_game/gui/screen_home_hr/mn_home_hr_rechph_idle.png')

While running game code:
IOError: Download error: network error ('images/base_game/gui/screen_home_hr/mn_home_hr_rechph_idle.png' > '/game/images/base_game/gui/screen_home_hr/mn_home_hr_rechph_idle.png')
# clear __builtin__._
# clear sys.path
# clear sys.argv
# clear sys.ps1
# clear sys.ps2
# clear sys.exitfunc
# clear sys.exc_type
# clear sys.exc_value
# clear sys.exc_traceback
# clear sys.last_type
# clear sys.last_value
# clear sys.last_traceback
# clear sys.path_hooks
# clear sys.path_importer_cache
# clear sys.meta_path
# clear sys.flags
# clear sys.float_info
# restore sys.stdin
# restore sys.stdout
# restore sys.stderr
